# -*- coding: utf-8 -*-
{
    'name': 'Salon and Spa Management',
    'summary': 'Saloon and spa management with online booking system',
    'version': '17.0.1.0.1',
    'author': 'Preciseways',
    'website': "",
    'Author': 'Preciseways',
    "category": "Industries",
    'depends': ['sale_management', 'account', 'purchase', 'base', 'base_setup', 'mail', 'website', 'hr_expense',
                'membership'],
    'data': [
        'security/salon_spa_management_groups.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/mail_template.xml',
        'data/salon_spa_chair_data.xml',
        'data/salon_spa_order_data.xml',
        'data/salon_spa_stages_data.xml',
        'wizard/salon_spa_report_wizard_views.xml',
        'wizard/create_commission_invoice.xml',
        'report/salon_spa_report.xml',
        'views/inherit_invoice_views.xml',
        'views/inherit_expence_views.xml',
        'views/inherit_product_views.xml',
        'views/inherit_purchase_order_views.xml',
        'views/res_partner_views.xml',
        'views/salon_spa_order_views.xml',
        'views/salon_spa_chair_views.xml',
        'views/salon_spa_booking_templates.xml',
        'views/salon_spa_booking_views.xml',
        'views/salon_spa_stage_views.xml',
        'views/inherit_membership_views.xml',
        'views/salon_spa_membership_views.xml',
        'views/commission_rules_views.xml',
        'views/employee_work_views.xml',
        'views/salon_spa_management_menus.xml',
        'views/salon_chairs.xml',

    ],

    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'price': 31,
    'currency': 'EUR',
    'assets': {
        'web.assets_backend': [
            'pways_salon_and_spa_management/static/src/css/salon_dashboard.css',
            'pways_salon_and_spa_management/static/src/less/salon_dashboard.less',
            'pways_salon_and_spa_management/static/src/xml/salon_dashboard.xml',
            'pways_salon_and_spa_management/static/src/js/salon_dashboard.js',
        ],
        'web.assets_frontend': [
            'pways_salon_and_spa_management/static/src/css/salon_website.css',
            'pways_salon_and_spa_management/static/src/js/website_salon_booking.js',
        ],
    },
}
