        
name: Deploy odoo17 🚀
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        TARGET:  /opt/odoo-one/addons/
        SSH_PRIVATE_KEY: ${{ secrets.odoo_mashael }}
        REMOTE_HOST: 84.247.174.94
        REMOTE_USER: root
        REMOTE_PORT: 22
        SCRIPT_AFTER: |
          sudo docker restart 05bb683549f2
