name: Deploy Odoo Project 🚀
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        TARGET: /opt/odoo-one/addons/  # Adjust to your actual Odoo directory path
        SSH_PRIVATE_KEY: ${{ secrets.odoo_mashael }}
        REMOTE_HOST: 84.247.174.94
        REMOTE_USER: root
        REMOTE_PORT: 22

    - name: Post-deployment Commands
      run: |
        echo "Running post-deployment commands..."
        CONTAINER_ID=$(docker ps -aqf "name=odoo-17")  # Adjust this to your container's name or filtering criteria
        if [ -z "$CONTAINER_ID" ]; then
          echo "No Odoo container found, skipping restart."
        else
          docker restart $CONTAINER_ID
          echo "Odoo container restarted."
        fi
        echo "Post-deployment tasks completed."    
